name: daily_routine_tracker
description: A comprehensive daily routine tracker application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5  # For state management
  shared_preferences: ^2.2.0  # For local storage
  intl: ^0.18.0  # For date formatting
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9  # For calendar view
  hive: ^2.2.3  # For local database
  hive_flutter: ^1.1.0  # Hive for Flutter
  path_provider: ^2.0.15  # For file paths
  uuid: ^4.5.1
  image_picker: ^1.1.2
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500